version: '3'
services:
  web:
    build: .
    command: gunicorn military_stuff.wsgi:application --bind 0.0.0.0:8000 --workers 1
    volumes:
    - .:/code
    ports:
    - "8000:8000"
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123